language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# ./gradlew 권한 부여이므로 필수!!
before_install:
  - chmod +x ./gradlew

# deploy 명령어가 실행되기 전에 수행
before_deploy:
  - zip -r hgko-springboot2-webservice *
  - mkdir -p deploy
  - mv hgko-springboot2-webservice.zip deploy/hgko-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: hgko-springboot2-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy 에서 생성한 디렉토리
    wait-until-deployd: true

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - khkkhk1207@gmail.com

